// ==============================================================================
// Runtime Memory Guardian
// File: include/rmg/rmg.hpp
//
// Umbrella header providing a single, convenient include point for the
// entire public API surface of Runtime Memory Guardian. Consumers who want
// the full facade experience need only:
//
//     #include <rmg/rmg.hpp>
//
// Consumers who want finer-grained control (e.g. to depend only on the
// memory-scanning layer without pulling in process orchestration) may
// instead include the specific headers they need directly, e.g.
// <rmg/memory/memory_scanner.hpp>.
// ==============================================================================

#pragma once

// Version information (generated by CMake from version.hpp.in).
#include <rmg/version.hpp>

// Symbol visibility macros.
#include <rmg/export.hpp>

// Core foundations.
#include <rmg/core/error.hpp>
#include <rmg/core/event.hpp>
#include <rmg/core/logger.hpp>
#include <rmg/core/non_copyable.hpp>
#include <rmg/core/types.hpp>

// Platform abstraction.
#include <rmg/platform/memory_region.hpp>
#include <rmg/platform/native_types.hpp>
#include <rmg/platform/platform_factory.hpp>
#include <rmg/platform/platform_traits.hpp>
#include <rmg/platform/process_handle.hpp>

// Memory scanning.
#include <rmg/memory/memory_diff.hpp>
#include <rmg/memory/memory_region_enumerator.hpp>
#include <rmg/memory/memory_scanner.hpp>
#include <rmg/memory/memory_snapshot.hpp>

// Integrity verification.
#include <rmg/integrity/code_section_info.hpp>
#include <rmg/integrity/hash_provider.hpp>
#include <rmg/integrity/integrity_baseline.hpp>
#include <rmg/integrity/integrity_checker.hpp>

// Hook detection.
#include <rmg/hooks/eat_hook_detector.hpp>
#include <rmg/hooks/hook_detector.hpp>
#include <rmg/hooks/hook_types.hpp>
#include <rmg/hooks/iat_hook_detector.hpp>
#include <rmg/hooks/inline_hook_detector.hpp>

// Module monitoring.
#include <rmg/modules/module_enumerator.hpp>
#include <rmg/modules/module_info.hpp>
#include <rmg/modules/module_monitor.hpp>

// Process orchestration.
#include <rmg/process/monitor_config.hpp>
#include <rmg/process/monitor_event.hpp>
#include <rmg/process/process_monitor.hpp>

// High-level facade (the recommended entry point for most consumers).
#include <rmg/api/runtime_memory_guardian.hpp>

/// @brief Root namespace of Runtime Memory Guardian.
///
/// Sub-namespaces:
///   - rmg::core       Shared foundations (error handling, logging, events).
///   - rmg::platform   OS abstraction layer (process handles, memory regions).
///   - rmg::memory     Memory scanning and snapshot/diff primitives.
///   - rmg::integrity  Code-section hashing and tamper detection.
///   - rmg::hooks      Inline/IAT/EAT hook detection (defensive, read-only).
///   - rmg::modules    Loaded-module enumeration and change monitoring.
///   - rmg::process    High-level continuous/on-demand monitoring orchestration.
///   - rmg::api        The RuntimeMemoryGuardian facade (recommended entry point).
namespace rmg {}